[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mbedtls = "0.8.1"
mbedtls-sys = "0.0.2"
serialport = "4.0.1"